#!/bin/bash
### BEGIN INIT INFO
# Provides: selenium
# Required-Start: $local_fs $network $remote_fs $xvfb-sel
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop Selenium
### END INIT INFO
#!/bin/bash
 
# TODO: http://wiki.debian.org/LSBInitScripts
 
DESC="Selenium server"
RUN_AS=root
JAVA_BIN=/usr/bin/java
 
SELENIUM_DIR=/var/lib/selenium
PID_FILE="$SELENIUM_DIR/selenium.pid"
JAR_FILE="$SELENIUM_DIR/selenium-server-standalone-2.39.0.jar"
LOG_FILE=/var/log/selenium.log

PORT="8015" 
MAX_MEMORY="-Xmx500m"
STACK_SIZE="-Xss1024k"
 
DAEMON_OPTS=" -client $MAX_MEMORY $STACK_SIZE -jar $JAR_FILE -port $PORT -log $LOG_FILE"
 
NAME=selenium
 
export DISPLAY=:99
 
case "$1" in
start)
echo -n "Starting $DESC: "
start-stop-daemon -c $RUN_AS --start --background --pidfile $PID_FILE --make-pidfile --exec $JAVA_BIN -- $DAEMON_OPTS
echo "$NAME."
;;
 
stop)
echo -n "Stopping $DESC: "
start-stop-daemon --stop --pidfile $PID_FILE
echo "$NAME."
;;
 
restart|force-reload)
echo -n "Restarting $DESC: "
start-stop-daemon --stop --pidfile $PID_FILE
sleep 1
start-stop-daemon -c $RUN_AS --start --background --pidfile $PID_FILE --make-pidfile --exec $JAVA_BIN -- $DAEMON_OPTS
echo "$NAME."
;;
 
*)
N=/etc/init.d/$NAME
echo "Usage: $N {start|stop|restart|force-reload}" >&2
exit 1
;;
esac



