#!/bin/bash
### BEGIN INIT INFO
# Provides: xvfb-pag
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop Xvfb for selenium
### END INIT INFO
XVFB=/usr/bin/Xvfb
XVFBARGS=":98 -screen 0 1024x768x24 -fbdir /var/run -ac"
PIDFILE=/var/run/xvfb-pag.pid
case "$1" in
start)
echo -n "Starting virtual X frame buffer: Xvfb"
start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $XVFB -- $XVFBARGS
echo "."
;;
stop)
echo -n "Stopping virtual X frame buffer: Xvfb"
start-stop-daemon --stop --quiet --pidfile $PIDFILE
echo "."
;;
restart)
$0 stop
$0 start
;;
*)
echo "Usage: /etc/init.d/xvfb-pag {start|stop|restart}"
exit 1
esac
 
exit 0
